### ISSUE TITLE
Update the schema diagram in the README file

### ISSUE THREAD

**Issue by claudenirmf** [OntoUML/ontouml-models#231]
The diagram containing the metadata's schema is incorrect, containing an inverted generalization between catalog and dataset, for instance.

Replace it and look for other issues.

![](https://user-images.githubusercontent.com/8641647/165767408-b526fa70-efa1-4661-b752-bf910778320c.png)

**Comment by pedropaulofb** [comment]
Thank you @claudenirmf  for registering that. Done.
