### ISSUE TITLE
UFO-A,B and C complete model(s)

### ISSUE THREAD

**Issue by hyprdia** [OntoUML/ontouml-models#285]
Hello,

First thank you for incredible work done on UFO and OntoUML. The papers and the general model of UFO have been of invaluable value for my project. 

I would like to know where can I access the latest complete UFO ontology model (A, B and C)? On the website [ontouml.org](https://ontouml.org/ontouml/metamodel-definitions/), there is models but they are quite old and among all the papers available from the team I have been unable to get a complete view of UFO (the main missing part is UFO-C as A and B have mostly been covered in the latest papers). 

Even an non-official version would be useful for my project. As a side note, would it be possible to know when the official complete UFO ontology model will be released? 

Thanks for your help,

Sébastien

**Comment by pedropaulofb** [comment]
Dear @hyprdia,

Unfortunately, there isn't a unified specification for UFO or OntoUML. The language evolve continuously as new academic papers are published. The information on ontouml.org is outdated. A somewhat more updated resource is available at [ontouml.readthedocs.io](https://ontouml.readthedocs.io/en/latest/), although it is still not fully current.

I suggest sharing more specific details about what you need, so we can provide you with the most recent resources.

**Comment by hyprdia** [comment]
Thank you for your prompt answer @pedropaulofb, 

I will go ask my question with more details there then.

**Comment by pedropaulofb** [comment]
Excellent! Please feel free to send there any questions you may have. 

We also have a WhatsApp group that we use for updates and sharing relevant information. If you would like to be added to the group, just send me an email.
